name: CI/CD - Machine Learning

on:
  workflow_dispatch:
  # push:
    # branches:
    # - main
      
# --------------------------------------------------------------
# VARIABLES GLOBALES
# --------------------------------------------------------------
env:
  # Docker Hub
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # Python-specific
  IMAGE_NAME: ml-service

jobs:
  # --------------------------------------------------------------
  # JOB 1: Build 路 Test 路 Docker
  # --------------------------------------------------------------
  build-and-push:
    name: Build 路 Test 路 Docker
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set Docker image tag
        id: set-tag
        run: |
          TAG=${GITHUB_SHA::8}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image
        run: |
          TAG=${{ steps.set-tag.outputs.tag }}
          IMAGE="docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:$TAG"
          docker build -t $IMAGE -f backend/python/Dockerfile backend/python
          docker push $IMAGE
