name: CI/CD - Machine Learning

on:
  workflow_dispatch:
  push:
    branches:
      # - main
      - feature/pipelines

# --------------------------------------------------------------
# VARIABLES GLOBALES
# --------------------------------------------------------------
env:
  # Docker Hub
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  # Python-specific
  IMAGE_NAME: ml-service

jobs:
  # --------------------------------------------------------------
  # JOB 1: Build · Docker
  # --------------------------------------------------------------
  build-and-push:
    name: Build · Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build & Push (linux/amd64)
        id: build
        uses: docker/build-push-action@v5
        with:
          context: backend/python
          file: backend/python/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy on Render
        if: ${{ success() && env.RENDER_DEPLOY_HOOK_URL != '' }}
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -fsS -X POST "$RENDER_DEPLOY_HOOK_URL"
